### ISSUE TITLE
Paleta de colores para la aplicación

### ISSUE THREAD

**Issue by ircsasw** [phpcfdi/app-descarga-masiva#6]
Se propone el uso de una paleta en tonos de rosa y colores pastel que combinen.

![image](https://user-images.githubusercontent.com/919978/138893930-78212003-a2fa-4c2e-9869-7223e79d187b.png)

**Comment by luffynando** [comment]
Propuesta tema claro, fondo rosa claro tendiendo a blanco, y uso resaltado de texto color primario o de énfasis, y combinación del uso entre primario, secundario y de énfasis. @ircsasw, @eclipxe13, @analagunas 

Paleta propuesta en Hexadecimal:

$primary        : #AD074D;
$secondary    : #F45899;
$accent          : #3A9492;
$background : #FAEDF7;


![image](https://user-images.githubusercontent.com/22108070/140586365-be301a33-b006-476d-aa0f-c202d2b7aa51.png)

**Comment by eclipxe13** [comment]
Me preocupa un poco la cercanía entre "negative" y "primary"

**Comment by luffynando** [comment]
@eclipxe13 haciendo una reducción en el color, a un rojo menos intenso se evita la cercanía quiza esta paleta te convenza mas?

![image](https://user-images.githubusercontent.com/22108070/140618862-526a04e5-524c-45e9-921a-e34772ab5fe5.png)
